//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse_Manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAYSININVENTORY
    {
        public int DAYSININVENTORY1 { get; set; }
    }
}
